<?php $title='Sonderbericht-Stammdaten'; ?>
<div class="page-header"><div><p class="eyebrow">Administration · Sonderberichte</p><h1>Einsatzarten & dynamische Felder</h1><p>Die Sonderberichtlogik bleibt systemweit einheitlich; Einsatzarten und Formularfelder sind standortbezogen.</p></div></div>
<div class="panel"><h2>Einsatzarten</h2><?php foreach($types as $t):?><form method="post" action="<?= e(url('admin/special-reports/type')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$t['id'] ?>"><label>Name<input name="name" value="<?= e($t['name']) ?>" required></label><label>Schlüssel<input name="code" value="<?= e($t['code']) ?>" required></label><label>Sortierung<input type="number" name="sort_order" value="<?= (int)$t['sort_order'] ?>"></label><label class="check-row"><input type="checkbox" name="force_section_enabled" value="1" <?= $t['force_section_enabled']?'checked':'' ?>><span>Zwangsmaßnahmen</span></label><label class="check-row"><input type="checkbox" name="active" value="1" <?= $t['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/special-reports/type')) ?>" class="compact-form"><?= csrf_field() ?><label>Name<input name="name" required></label><label>Schlüssel<input name="code" required></label><label>Sortierung<input type="number" name="sort_order" value="100"></label><label class="check-row"><input type="checkbox" name="force_section_enabled" value="1"><span>Zwangsmaßnahmen</span></label><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Einsatzart</button></form></div>
<div class="panel"><h2>Dynamische Formularfelder</h2>
<?php foreach($fields as $f):$vis=(array)($f['visibility']??[]);?>
<form method="post" action="<?= e(url('admin/special-reports/dynamic-field')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$f['id'] ?>">
<label>Einsatzart<select name="definition_id"><?php foreach($types as $t):?><option value="<?= (int)$t['id'] ?>" <?= (int)$f['definition_id']===(int)$t['id']?'selected':'' ?>><?= e($t['name']) ?></option><?php endforeach;?></select></label>
<label>Schlüssel<input name="field_key" value="<?= e($f['field_key']) ?>" required></label><label>Bezeichnung<input name="label" value="<?= e($f['label']) ?>" required></label>
<label>Abschnitt<input name="section_name" value="<?= e($f['section_name']??'Zusatzangaben') ?>" required></label>
<label>Typ<select name="field_type"><?php foreach(['text','textarea','number','date','time','datetime','select','multiselect','checkbox','yesno'] as $t):?><option value="<?= e($t) ?>" <?= $f['field_type']===$t?'selected':'' ?>><?= e($t) ?></option><?php endforeach;?></select></label>
<label>Optionen<textarea name="options"><?= e(implode("\n",(array)($f['options']??[]))) ?></textarea></label><label>Sortierung<input type="number" name="sort_order" value="<?= (int)$f['sort_order'] ?>"></label>
<label>Anzeigen wenn<select name="visibility_field_id"><option value="">Immer anzeigen</option><?php foreach($fields as $candidate):if((int)$candidate['definition_id']!==(int)$f['definition_id']||(int)$candidate['id']===(int)$f['id']||(int)$candidate['sort_order']>=(int)$f['sort_order'])continue;?><option value="<?= (int)$candidate['id'] ?>" <?= (int)($vis['field_id']??0)===(int)$candidate['id']?'selected':'' ?>><?= e($candidate['label']) ?></option><?php endforeach;?></select></label>
<label>gleich Wert<input name="visibility_value" value="<?= e($vis['value']??'') ?>" placeholder="z. B. ja"></label>
<label class="check-row"><input type="checkbox" name="required" value="1" <?= $f['required']?'checked':'' ?>><span>Pflicht</span></label><label class="check-row"><input type="checkbox" name="active" value="1" <?= $f['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form>
<?php endforeach;?>
<form method="post" action="<?= e(url('admin/special-reports/dynamic-field')) ?>" class="compact-form"><?= csrf_field() ?>
<label>Einsatzart<select name="definition_id"><?php foreach($types as $t):?><option value="<?= (int)$t['id'] ?>"><?= e($t['name']) ?></option><?php endforeach;?></select></label>
<label>Schlüssel<input name="field_key" required></label><label>Bezeichnung<input name="label" required></label><label>Abschnitt<input name="section_name" value="Zusatzangaben" required></label>
<label>Typ<select name="field_type"><?php foreach(['text','textarea','number','date','time','datetime','select','multiselect','checkbox','yesno'] as $t):?><option value="<?= e($t) ?>"><?= e($t) ?></option><?php endforeach;?></select></label>
<label>Optionen<textarea name="options"></textarea></label><label>Sortierung<input type="number" name="sort_order" value="100"></label>
<label>Anzeigen wenn<select name="visibility_field_id"><option value="">Immer anzeigen</option><?php foreach($fields as $candidate):?><option value="<?= (int)$candidate['id'] ?>"><?= e($candidate['type_name'].' · '.$candidate['label']) ?></option><?php endforeach;?></select></label>
<label>gleich Wert<input name="visibility_value" placeholder="z. B. ja"></label>
<label class="check-row"><input type="checkbox" name="required" value="1"><span>Pflicht</span></label><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Feld</button></form></div>
