<?php $title='Statistik'; ?>
<div class="page-header"><div><p class="eyebrow">Statistik</p><h1>Auswertungen</h1><p>Kennzahlen und Drill-down für den aktiven Standort.</p></div></div>
<div class="panel"><form method="get" action="<?= e(url('statistics')) ?>" class="filterbar"><input type="date" name="from" value="<?= e($from) ?>"><input type="date" name="to" value="<?= e($to) ?>"><button class="button primary" type="submit">Zeitraum anwenden</button></form></div>
<div class="metric-grid">
<a class="metric-card" href="<?= e(url('dutybook/search?from='.$from.'&to='.$to)) ?>"><span class="metric-icon">▤</span><div><small>Dienstbucheinträge</small><strong><?= (int)$summary['dutybook'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('special-reports/search?from='.$from.'&to='.$to)) ?>"><span class="metric-icon">▧</span><div><small>Sonderberichte</small><strong><?= (int)$summary['special_reports'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('special-reports/search?from='.$from.'&to='.$to.'&status=completed')) ?>"><span class="metric-icon">!</span><div><small>Ungeprüft</small><strong><?= (int)$summary['unreviewed'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('valuables/search?stored_from='.$from.'&stored_to='.$to)) ?>"><span class="metric-icon">▣</span><div><small>Einlagerungen</small><strong><?= (int)$summary['valuables_stored'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('valuables/search?released_from='.$from.'&released_to='.$to)) ?>"><span class="metric-icon">↗</span><div><small>Auslagerungen</small><strong><?= (int)$summary['valuables_released'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('house-bans?from='.$from.'&to='.$to)) ?>"><span class="metric-icon">⊘</span><div><small>Hausverbote</small><strong><?= (int)$summary['house_bans'] ?></strong></div></a>
</div>
<div class="panel"><div class="panel-header"><div><h2>Durchschnittliche Verwahrdauer</h2><p>Vollständig ausgelagerte Vorgänge im gewählten Zeitraum.</p></div><strong><?= e(number_format((float)$summary['avg_storage_days'],1,',','.')) ?> Tage</strong></div></div>
<div class="two-col"><div class="panel"><h2>Dienstbuch · häufigste Ereignisarten</h2><div class="chart-box"><canvas data-chart="bar" data-labels="<?= e(json_encode(array_column($events,'label'),JSON_UNESCAPED_UNICODE)) ?>" data-values="<?= e(json_encode(array_map('intval',array_column($events,'value')))) ?>"></canvas></div><div class="timeline-list"><?php foreach($events as $x):?><a class="timeline-item" href="<?= e(url('dutybook/search?from='.$from.'&to='.$to.'&event_type_id='.(int)$x['event_type_id'])) ?>"><strong><?= e($x['label']) ?></strong><span><?= (int)$x['value'] ?></span></a><?php endforeach;?></div></div>
<div class="panel"><h2>Sonderberichte · Einsatzarten</h2><div class="chart-box"><canvas data-chart="pie" data-labels="<?= e(json_encode(array_column($reportTypes,'label'),JSON_UNESCAPED_UNICODE)) ?>" data-values="<?= e(json_encode(array_map('intval',array_column($reportTypes,'value')))) ?>"></canvas></div><div class="timeline-list"><?php foreach($reportTypes as $x):?><a class="timeline-item" href="<?= e(url('special-reports/search?from='.$from.'&to='.$to.'&type_id='.(int)$x['type_id'])) ?>"><strong><?= e($x['label']) ?></strong><span><?= (int)$x['value'] ?></span></a><?php endforeach;?></div></div></div>
<div class="panel"><h2>Vorgänge im Zeitverlauf</h2><div class="chart-box wide-chart"><canvas data-chart="line" data-labels="<?= e(json_encode(array_column($timeline,'day'),JSON_UNESCAPED_UNICODE)) ?>" data-values="<?= e(json_encode(array_map('intval',array_column($timeline,'value')))) ?>"></canvas></div></div>
