<?php
$title='Statistik';
$dutyMetric=['from'=>$from,'to'=>$to];if($eventTypeId)$dutyMetric['event_type_id']=$eventTypeId;
$reportMetric=['from'=>$from,'to'=>$to];if($reportTypeId)$reportMetric['type_id']=$reportTypeId;
$eventUrls=[];foreach($events as $row){$params=['from'=>$from,'to'=>$to];if((int)($row['event_type_id']??0)>0)$params['event_type_id']=(int)$row['event_type_id'];else $params['automatic']=1;$eventUrls[]=url('dutybook/search?'.http_build_query($params));}
$reportUrls=[];foreach($reportTypes as $row)$reportUrls[]=url('special-reports/search?'.http_build_query(['from'=>$from,'to'=>$to,'type_id'=>(int)$row['type_id']]));
$timelineUrls=[];foreach($timeline as $row){$params=['day'=>$row['day']];if($eventTypeId)$params['event_type_id']=$eventTypeId;if($reportTypeId)$params['report_type_id']=$reportTypeId;$timelineUrls[]=url('statistics/drilldown?'.http_build_query($params));}
?>
<div class="page-header split"><div><p class="eyebrow">Statistik</p><h1>Auswertungen</h1><p>Kennzahlen und Drill-down für den aktiven Standort.</p></div><?php if(can('statistics.export')):$exportQuery=http_build_query(['from'=>$from,'to'=>$to,'event_type_id'=>$eventTypeId?:null,'report_type_id'=>$reportTypeId?:null]);?><div class="inline-actions"><a class="button ghost" href="<?= e(url('statistics-export.csv?'.$exportQuery)) ?>">CSV</a><a class="button ghost" href="<?= e(url('statistics-export.pdf?'.$exportQuery)) ?>">PDF</a></div><?php endif;?></div>
<div class="panel"><form method="get" action="<?= e(url('statistics')) ?>" class="form-grid"><label>Von<input type="date" name="from" value="<?= e($from) ?>"></label><label>Bis<input type="date" name="to" value="<?= e($to) ?>"></label><label>Ereignisart Dienstbuch<select name="event_type_id"><option value="">Alle</option><?php foreach($eventTypes as $t):?><option value="<?= (int)$t['id'] ?>" <?= $eventTypeId===(int)$t['id']?'selected':'' ?>><?= e($t['name']) ?></option><?php endforeach;?></select></label><label>Einsatzart Sonderbericht<select name="report_type_id"><option value="">Alle</option><?php foreach($specialReportTypes as $t):?><option value="<?= (int)$t['id'] ?>" <?= $reportTypeId===(int)$t['id']?'selected':'' ?>><?= e($t['name']) ?></option><?php endforeach;?></select></label><div class="span-2 form-actions"><button class="button primary" type="submit">Filter anwenden</button></div></form><p class="muted">Standortfilter: aktiver Standort. Ein anderer Standort kann jederzeit oben im System ausgewählt werden.</p></div>
<div class="metric-grid">
<a class="metric-card" href="<?= e(url('dutybook/search?'.http_build_query($dutyMetric))) ?>"><span class="metric-icon">▤</span><div><small>Dienstbucheinträge</small><strong><?= (int)$summary['dutybook'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('special-reports/search?'.http_build_query($reportMetric))) ?>"><span class="metric-icon">▧</span><div><small>Sonderberichte</small><strong><?= (int)$summary['special_reports'] ?></strong></div></a>
<?php $unreviewedMetric=$reportMetric+['status'=>'completed'];?><a class="metric-card" href="<?= e(url('special-reports/search?'.http_build_query($unreviewedMetric))) ?>"><span class="metric-icon">!</span><div><small>Ungeprüft</small><strong><?= (int)$summary['unreviewed'] ?></strong></div></a>
<a class="metric-card" href="<?= e(url('valuables/search?stored_from='.$from.'&stored_to='.$to)) ?>"><span class="metric-icon">▣</span><div><small>Einlagerungen</small><strong><?= (int)$summary['valuables_stored'] ?></strong></div></a>
<?php if(can('valuables.archive')):?><a class="metric-card" href="<?= e(url('valuables/archive?'.http_build_query(['released_from'=>$from,'released_to'=>$to]))) ?>"><span class="metric-icon">↗</span><div><small>Auslagerungen</small><strong><?= (int)$summary['valuables_released'] ?></strong></div></a><?php else:?><div class="metric-card"><span class="metric-icon">↗</span><div><small>Auslagerungen</small><strong><?= (int)$summary['valuables_released'] ?></strong></div></div><?php endif;?>
<a class="metric-card" href="<?= e(url('house-bans?from='.$from.'&to='.$to)) ?>"><span class="metric-icon">⊘</span><div><small>Hausverbote</small><strong><?= (int)$summary['house_bans'] ?></strong></div></a>
</div>
<div class="panel"><div class="panel-header"><div><h2>Durchschnittliche Verwahrdauer</h2><p>Vollständig ausgelagerte Vorgänge im gewählten Zeitraum.</p></div><strong><?= e(number_format((float)$summary['avg_storage_days'],1,',','.')) ?> Tage</strong></div></div>
<div class="two-col"><div class="panel"><h2>Dienstbuch · häufigste Ereignisarten</h2><div class="chart-box"><canvas data-chart="bar" data-labels="<?= e(json_encode(array_column($events,'label'),JSON_UNESCAPED_UNICODE)) ?>" data-values="<?= e(json_encode(array_map('intval',array_column($events,'value')))) ?>" data-urls="<?= e(json_encode($eventUrls,JSON_UNESCAPED_SLASHES)) ?>"></canvas></div><div class="timeline-list"><?php foreach($events as $x):?><a class="timeline-item" href="<?= e(url('dutybook/search?from='.$from.'&to='.$to.'&event_type_id='.(int)$x['event_type_id'])) ?>"><strong><?= e($x['label']) ?></strong><span><?= (int)$x['value'] ?></span></a><?php endforeach;?></div></div>
<div class="panel"><h2>Sonderberichte · Einsatzarten</h2><div class="chart-box"><canvas data-chart="pie" data-labels="<?= e(json_encode(array_column($reportTypes,'label'),JSON_UNESCAPED_UNICODE)) ?>" data-values="<?= e(json_encode(array_map('intval',array_column($reportTypes,'value')))) ?>" data-urls="<?= e(json_encode($reportUrls,JSON_UNESCAPED_SLASHES)) ?>"></canvas></div><div class="timeline-list"><?php foreach($reportTypes as $x):?><a class="timeline-item" href="<?= e(url('special-reports/search?from='.$from.'&to='.$to.'&type_id='.(int)$x['type_id'])) ?>"><strong><?= e($x['label']) ?></strong><span><?= (int)$x['value'] ?></span></a><?php endforeach;?></div></div></div>
<div class="panel"><h2>Vorgänge im Zeitverlauf</h2><div class="chart-box wide-chart"><canvas data-chart="line" data-labels="<?= e(json_encode(array_column($timeline,'day'),JSON_UNESCAPED_UNICODE)) ?>" data-values="<?= e(json_encode(array_map('intval',array_column($timeline,'value')))) ?>" data-urls="<?= e(json_encode($timelineUrls,JSON_UNESCAPED_SLASHES)) ?>"></canvas></div></div>
