<?php
$editing=is_array($record);$title=$editing?'Mitteilung bearbeiten':'Mitteilung erstellen';
$targets=$record['targets']??[];$all=false;$targetLocations=[];$targetRoles=[];
foreach($targets as $t){if($t['target_type']==='all')$all=true;elseif($t['target_type']==='location')$targetLocations[]=(int)$t['target_value'];elseif($t['target_type']==='role')$targetRoles[]=$t['target_value'];}
?>
<div class="page-header split"><div><p class="eyebrow">Mitteilungen</p><h1><?= e($title) ?></h1><p>Veröffentlichte Änderungen werden protokolliert und als „aktualisiert“ angezeigt.</p></div><a class="button ghost" href="<?= e(url('announcements/manage')) ?>">Zurück</a></div>
<form method="post" enctype="multipart/form-data" action="<?= e($editing?url('announcements/'.$record['id']):url('announcements')) ?>" class="panel form-grid" data-unsaved-warning><?= csrf_field() ?>
<label class="span-2">Titel*<input name="title" required value="<?= e(old('title',$record['title']??'')) ?>"></label>
<label class="span-2">Text*<textarea name="body" rows="10" required><?= e(old('body',$record['body']??'')) ?></textarea></label>
<label>Priorität<select name="priority"><option value="info" <?= old('priority',$record['priority']??'info')==='info'?'selected':'' ?>>Info</option><option value="important" <?= old('priority',$record['priority']??'')==='important'?'selected':'' ?>>Wichtig</option></select></label>
<label>Status<select name="status"><option value="draft" <?= old('status',$record['status']??'draft')==='draft'?'selected':'' ?>>Entwurf</option><option value="scheduled" <?= old('status',$record['status']??'')==='scheduled'?'selected':'' ?>>Geplant</option><option value="published" <?= old('status',$record['status']??'')==='published'?'selected':'' ?>>Veröffentlicht</option><option value="archived" <?= old('status',$record['status']??'')==='archived'?'selected':'' ?>>Archiviert</option></select></label>
<label>Gültigkeitsbeginn<input type="datetime-local" name="valid_from" value="<?= e(($v=old('valid_from',$record['valid_from']??''))?str_replace(' ','T',substr((string)$v,0,16)):'') ?>"></label>
<label>Gültigkeitsende<input type="datetime-local" name="valid_until" value="<?= e(($v=old('valid_until',$record['valid_until']??''))?str_replace(' ','T',substr((string)$v,0,16)):'') ?>"></label>
<label class="check-row span-2"><input type="checkbox" name="require_ack" value="1" <?= old('require_ack',$record['require_ack']??0)?'checked':'' ?>><span>Lesebestätigung erforderlich</span></label>
<fieldset class="span-2 checkbox-panel"><legend>Zielgruppen</legend><label class="check-row"><input type="checkbox" name="target_all" value="1" <?= $all?'checked':'' ?>><span>Alle Benutzer</span></label><h3 class="section-title">Standorte</h3><div class="checkbox-stack"><?php foreach($locations as $l):?><label class="check-row"><input type="checkbox" name="target_locations[]" value="<?= (int)$l['id'] ?>" <?= in_array((int)$l['id'],$targetLocations,true)?'checked':'' ?>><span><?= e($l['name']) ?></span></label><?php endforeach;?></div><h3 class="section-title">Rollen</h3><div class="checkbox-stack"><?php foreach($roles as $r):?><label class="check-row"><input type="checkbox" name="target_roles[]" value="<?= e($r['code']) ?>" <?= in_array($r['code'],$targetRoles,true)?'checked':'' ?>><span><?= e($r['name']) ?></span></label><?php endforeach;?></div></fieldset>
<label class="span-2">Anhänge<input type="file" name="attachments[]" multiple accept=".jpg,.jpeg,.png,.pdf"><small>Bilder und PDF.</small></label>
<div class="span-2 form-actions"><button class="button primary" type="submit">Mitteilung speichern</button></div></form>
