<?php $title='Dienstbuch-Stammdaten'; ?>
<div class="page-header"><div><p class="eyebrow">Administration · Dienstbuch</p><h1>Stammdaten & Formulare</h1><p>Schichten, Ereignisarten, Zusatzfelder, Orte, Maßnahmen, Personenrollen und externe Stellen.</p></div></div>
<div class="notice info">Änderungen an Stammdaten werden protokolliert. Bestehende Dienstbucheinträge behalten ihre gespeicherten Werte und Verknüpfungen.</div>


<div class="panel config-section">
    <div class="panel-header"><div><h2>Automatische Dienstbucheinträge</h2><p>Standortbezogene Systemereignisse können einzeln ein- oder ausgeschaltet werden.</p></div></div>
    <div class="notice info">Bei einem direkt erstellten Sonderbericht ohne bestehenden Dienstbucheintrag wird die fachlich notwendige Dienstbuchverknüpfung trotzdem erzeugt. Der Schalter „Sonderbericht erstellt“ steuert nur den zusätzlichen automatischen Eintrag, wenn bereits ein Dienstbucheintrag als Quelle existiert.</div>
    <?php foreach($automaticRules as $rule): ?>
        <form method="post" action="<?= e(url('admin/dutybook/automatic-rule')) ?>" class="compact-form">
            <?= csrf_field() ?>
            <input type="hidden" name="event_code" value="<?= e($rule['event_code']) ?>">
            <div><strong><?= e($rule['label']) ?></strong><small class="table-sub"><?= e($rule['event_code']) ?></small></div>
            <label class="check-row"><input type="checkbox" name="enabled" value="1" <?= $rule['enabled']?'checked':'' ?>><span>Automatischen Eintrag erzeugen</span></label>
            <button class="button secondary" type="submit">Speichern</button>
        </form>
    <?php endforeach; ?>
</div>


<div class="panel config-section"><h2>Schichten</h2><?php foreach($shifts as $x):?><form method="post" action="<?= e(url('admin/dutybook/shift')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Kürzel<input name="code" value="<?= e($x['code']) ?>" required></label><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><label>Beginn<input type="time" name="start_time" value="<?= e(substr($x['start_time'],0,5)) ?>" required></label><label>Ende<input type="time" name="end_time" value="<?= e(substr($x['end_time'],0,5)) ?>" required></label><label>Sortierung<input type="number" name="sort_order" value="<?= (int)$x['sort_order'] ?>"></label><label class="check-row"><input type="checkbox" name="crosses_midnight" value="1" <?= $x['crosses_midnight']?'checked':'' ?>><span>über Mitternacht</span></label><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?>
<form method="post" action="<?= e(url('admin/dutybook/shift')) ?>" class="compact-form"><?= csrf_field() ?><label>Kürzel<input name="code" required></label><label>Name<input name="name" required></label><label>Beginn<input type="time" name="start_time" required></label><label>Ende<input type="time" name="end_time" required></label><label>Sortierung<input type="number" name="sort_order" value="50"></label><label class="check-row"><input type="checkbox" name="crosses_midnight" value="1"><span>über Mitternacht</span></label><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Schicht</button></form></div>

<div class="panel config-section"><h2>Kategorien</h2><?php foreach($categories as $x):?><form method="post" action="<?= e(url('admin/dutybook/category')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><label>Sortierung<input type="number" name="sort_order" value="<?= (int)$x['sort_order'] ?>"></label><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/category')) ?>" class="compact-form"><?= csrf_field() ?><label>Name<input name="name" required></label><label>Sortierung<input type="number" name="sort_order" value="100"></label><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Kategorie</button></form></div>

<div class="panel config-section"><h2>Ereignisarten</h2><?php foreach($eventTypes as $x):?><form method="post" action="<?= e(url('admin/dutybook/event-type')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Kategorie<select name="category_id"><?php foreach($categories as $c):?><option value="<?= (int)$c['id'] ?>" <?= (int)$x['category_id']===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach;?></select></label><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><label>Sortierung<input type="number" name="sort_order" value="<?= (int)$x['sort_order'] ?>"></label><label class="check-row"><input type="checkbox" name="offer_special_report" value="1" <?= $x['offer_special_report']?'checked':'' ?>><span>Sonderbericht</span></label><label class="check-row"><input type="checkbox" name="offer_valuables" value="1" <?= $x['offer_valuables']?'checked':'' ?>><span>Wertsache</span></label><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/event-type')) ?>" class="compact-form"><?= csrf_field() ?><label>Kategorie<select name="category_id"><?php foreach($categories as $c):?><option value="<?= (int)$c['id'] ?>"><?= e($c['name']) ?></option><?php endforeach;?></select></label><label>Name<input name="name" required></label><label>Sortierung<input type="number" name="sort_order" value="100"></label><label class="check-row"><input type="checkbox" name="offer_special_report" value="1"><span>Sonderbericht</span></label><label class="check-row"><input type="checkbox" name="offer_valuables" value="1"><span>Wertsache</span></label><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><input type="hidden" name="auto_entry_enabled" value="1"><button class="button primary" type="submit">+ Ereignisart</button></form></div>

<div class="panel config-section"><h2>Dynamische Zusatzfelder</h2><?php foreach($dynamicFields as $x):?><form method="post" action="<?= e(url('admin/dutybook/dynamic-field')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Ereignisart<select name="definition_id"><?php foreach($eventTypes as $eType):?><option value="<?= (int)$eType['id'] ?>" <?= (int)$x['definition_id']===(int)$eType['id']?'selected':'' ?>><?= e($eType['name']) ?></option><?php endforeach;?></select></label><label>Schlüssel<input name="field_key" value="<?= e($x['field_key']) ?>" required></label><label>Bezeichnung<input name="label" value="<?= e($x['label']) ?>" required></label><label>Typ<select name="field_type"><?php foreach(['text','textarea','number','date','time','datetime','select','multiselect','checkbox','yesno'] as $t):?><option value="<?= e($t) ?>" <?= $x['field_type']===$t?'selected':'' ?>><?= e($t) ?></option><?php endforeach;?></select></label><label>Optionen, je Zeile<textarea name="options"><?= e(implode("\n",json_decode((string)$x['options_json'],true)?:[])) ?></textarea></label><label class="check-row"><input type="checkbox" name="required" value="1" <?= $x['required']?'checked':'' ?>><span>Pflicht</span></label><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><input type="hidden" name="sort_order" value="<?= (int)$x['sort_order'] ?>"><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/dynamic-field')) ?>" class="compact-form"><?= csrf_field() ?><label>Ereignisart<select name="definition_id"><?php foreach($eventTypes as $x):?><option value="<?= (int)$x['id'] ?>"><?= e($x['name']) ?></option><?php endforeach;?></select></label><label>Schlüssel<input name="field_key" required placeholder="z_b_aktenzeichen"></label><label>Bezeichnung<input name="label" required></label><label>Typ<select name="field_type"><?php foreach(['text','textarea','number','date','time','datetime','select','multiselect','checkbox','yesno'] as $t):?><option value="<?= e($t) ?>"><?= e($t) ?></option><?php endforeach;?></select></label><label>Optionen, je Zeile<textarea name="options"></textarea></label><label class="check-row"><input type="checkbox" name="required" value="1"><span>Pflicht</span></label><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><input type="hidden" name="sort_order" value="100"><button class="button primary" type="submit">+ Feld</button></form></div>

<div class="two-col"><div class="panel config-section"><h2>Orte</h2><?php foreach($places as $x):?><form method="post" action="<?= e(url('admin/dutybook/place')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Typ<select name="place_type"><?php foreach(['building'=>'Gebäude','floor'=>'Etage','area'=>'Bereich','room'=>'Raum','station'=>'Station'] as $v=>$l):?><option value="<?= e($v) ?>" <?= $x['place_type']===$v?'selected':'' ?>><?= e($l) ?></option><?php endforeach;?></select></label><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><label>Übergeordnet<select name="parent_id"><option value="">–</option><?php foreach($places as $p):if((int)$p['id']===(int)$x['id'])continue;?><option value="<?= (int)$p['id'] ?>" <?= (int)$x['parent_id']===(int)$p['id']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach;?></select></label><input type="hidden" name="sort_order" value="<?= (int)$x['sort_order'] ?>"><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/place')) ?>" class="compact-form"><?= csrf_field() ?><label>Typ<select name="place_type"><option value="building">Gebäude</option><option value="floor">Etage</option><option value="area">Bereich</option><option value="room">Raum</option><option value="station">Station</option></select></label><label>Name<input name="name" required></label><label>Übergeordnet<select name="parent_id"><option value="">–</option><?php foreach($places as $p):?><option value="<?= (int)$p['id'] ?>"><?= e($p['name']) ?></option><?php endforeach;?></select></label><input type="hidden" name="sort_order" value="100"><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Ort</button></form></div>
<div class="panel config-section"><h2>Maßnahmen</h2><?php foreach($measures as $x):?><form method="post" action="<?= e(url('admin/dutybook/measure')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><input type="hidden" name="sort_order" value="<?= (int)$x['sort_order'] ?>"><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/measure')) ?>" class="compact-form"><?= csrf_field() ?><label>Name<input name="name" required></label><input type="hidden" name="sort_order" value="100"><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Maßnahme</button></form></div></div>

<div class="two-col"><div class="panel config-section"><h2>Personenrollen</h2><?php foreach($personRoles as $x):?><form method="post" action="<?= e(url('admin/dutybook/person-role')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><input type="hidden" name="sort_order" value="<?= (int)$x['sort_order'] ?>"><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/person-role')) ?>" class="compact-form"><?= csrf_field() ?><label>Name<input name="name" required></label><input type="hidden" name="sort_order" value="100"><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Rolle</button></form></div>
<div class="panel config-section"><h2>Externe Stellen</h2><?php foreach($externalOrganizations as $x):?><form method="post" action="<?= e(url('admin/dutybook/external')) ?>" class="compact-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$x['id'] ?>"><label>Typ<input name="organization_type" value="<?= e($x['organization_type']) ?>" required></label><label>Name<input name="name" value="<?= e($x['name']) ?>" required></label><input type="hidden" name="sort_order" value="<?= (int)$x['sort_order'] ?>"><label class="check-row"><input type="checkbox" name="active" value="1" <?= $x['active']?'checked':'' ?>><span>Aktiv</span></label><button class="button secondary" type="submit">Speichern</button></form><?php endforeach;?><form method="post" action="<?= e(url('admin/dutybook/external')) ?>" class="compact-form"><?= csrf_field() ?><label>Typ<input name="organization_type" required></label><label>Name<input name="name" required></label><input type="hidden" name="sort_order" value="100"><label class="check-row"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="button primary" type="submit">+ Stelle</button></form></div></div>
