<?php $title='Dienstbucheintrag'; ?>
<div class="page-header split"><div><p class="eyebrow">Dienstbuch · <?= e($entry['duty_date']) ?></p><h1><?= e($entry['is_automatic']?'Automatischer Eintrag':($entry['event_type_name']??'Dienstbucheintrag')) ?></h1><p>Erfasst von <?= e($entry['creator_name']??'System') ?> am <?= e(format_datetime($entry['created_at'])) ?></p></div><div class="inline-actions"><a class="button ghost" href="<?= e(url('dutybook?date='.$entry['duty_date'])) ?>">Tagesdienstbuch</a><?php if(!$entry['is_automatic']&&!$locked&&can('dutybook.edit')):?><a class="button primary" href="<?= e(url('dutybook/'.$entry['id'].'/edit')) ?>">Bearbeiten</a><?php endif;?></div></div>
<div class="panel">
<div class="detail-grid">
<div class="detail-item"><small>Datum/Uhrzeit</small><strong><?= e(format_datetime($entry['occurred_at'])) ?></strong></div><div class="detail-item"><small>Schicht</small><strong><?= e($entry['shift_name']??'–') ?></strong></div><div class="detail-item"><small>Status</small><span class="badge status-<?= e($entry['status']) ?>"><?= e(match($entry['status']){'open'=>'Offen','in_progress'=>'In Bearbeitung','done'=>'Erledigt','handover'=>'Zur Übergabe',default=>$entry['status']}) ?></span></div>
<div class="detail-item"><small>Kategorie</small><strong><?= e($entry['category_name']??'–') ?></strong></div><div class="detail-item"><small>Ereignisart</small><strong><?= e($entry['event_type_name']??'–') ?></strong></div><div class="detail-item"><small>Ort</small><strong><?= e(trim(($entry['place_name']??'').' '.($entry['place_free_text']??''))?:'–') ?></strong></div>
<div class="detail-item wide"><small>Sachverhalt</small><div class="prose"><?= e($entry['facts']) ?></div></div>
<?php if($entry['measures_text']):?><div class="detail-item wide"><small>Maßnahmen</small><div class="prose"><?= e($entry['measures_text']) ?></div></div><?php endif;?>
<?php if($entry['result_text']):?><div class="detail-item wide"><small>Ergebnis</small><div class="prose"><?= e($entry['result_text']) ?></div></div><?php endif;?>
</div>
<?php if($entry['dynamic_values']):?><h3 class="section-title">Zusatzfelder</h3><div class="detail-grid"><?php foreach($entry['dynamic_values'] as $v):?><div class="detail-item"><small><?= e($v['label']) ?></small><strong><?= e(is_array($v['value'])?implode(', ',$v['value']):(is_bool($v['value'])?($v['value']?'Ja':'Nein'):$v['value'])) ?></strong></div><?php endforeach;?></div><?php endif;?>
<?php if($entry['staff']):?><h3 class="section-title">Beteiligte Mitarbeiter</h3><p><?= e(implode(', ',array_map(fn($u)=>$u['first_name'].' '.$u['last_name'],$entry['staff']))) ?></p><?php endif;?>
<?php if($entry['people']):?><h3 class="section-title">Beteiligte Personen</h3><div class="table-wrap"><table><thead><tr><th>Rolle</th><th>Name</th><th>Geburtsdatum</th><th>Bereich</th><th>Kennung</th></tr></thead><tbody><?php foreach($entry['people'] as $p):?><tr><td><?= e($p['role_name']??$p['person_type']??'–') ?></td><td><?= e(trim(($p['first_name']??'').' '.($p['last_name']??''))?:'–') ?></td><td><?= e($p['birth_date']??'–') ?></td><td><?= e($p['area']??'–') ?></td><td><?= e($p['internal_identifier']??'–') ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if($entry['measures']):?><h3 class="section-title">Strukturierte Maßnahmen</h3><p><?= e(implode(', ',array_column($entry['measures'],'name'))) ?></p><?php endif;?>
<?php if($entry['external']):?><h3 class="section-title">Externe Stellen</h3><div class="table-wrap"><table><thead><tr><th>Organisation</th><th>Ansprechpartner</th><th>Zeit</th><th>Vorgang</th><th>Rückmeldung</th></tr></thead><tbody><?php foreach($entry['external'] as $x):?><tr><td><?= e($x['organization_master_name']??$x['organization_name']??'–') ?></td><td><?= e($x['contact_name']??'–') ?></td><td><?= e(format_datetime($x['notified_at'])) ?></td><td><?= e($x['reference_number']??'–') ?></td><td><?= e($x['feedback']??'–') ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if($entry['attachments']):?><h3 class="section-title">Anhänge</h3><div class="timeline-list"><?php foreach($entry['attachments'] as $a):?><div class="timeline-item"><a href="<?= e(url('attachments/'.$a['id'].'/download')) ?>"><strong><?= e($a['original_name']) ?></strong></a><small class="table-sub"><?= e($a['mime_type']) ?> · <?= e(format_datetime($a['uploaded_at'])) ?> · <?= e($a['uploader_name']??'') ?></small></div><?php endforeach;?></div><?php endif;?>
<?php if($entry['addenda']):?><h3 class="section-title">Dokumentierte Nachträge</h3><div class="timeline-list"><?php foreach($entry['addenda'] as $a):?><div class="timeline-item"><strong><?= e($a['reason']) ?></strong><small class="table-sub"><?= e($a['user_name']??'') ?> · <?= e(format_datetime($a['created_at'])) ?></small></div><?php endforeach;?></div><?php endif;?>
</div>
<?php if(!$entry['is_automatic']&&$locked&&can('dutybook.addendum')):?><div class="panel"><div class="panel-header"><div><h2>Nachtrag</h2><p>Die reguläre Bearbeitungsfrist ist abgelaufen. Jede Änderung wird mit Alt-/Neustand protokolliert.</p></div></div><form method="post" action="<?= e(url('dutybook/'.$entry['id'].'/addendum')) ?>" class="stack-form"><?= csrf_field() ?><label>Änderungsgrund*<input name="reason" required></label><label>Status<select name="status"><?php foreach(['open'=>'Offen','in_progress'=>'In Bearbeitung','done'=>'Erledigt','handover'=>'Zur Übergabe'] as $v=>$l):?><option value="<?= e($v) ?>" <?= $entry['status']===$v?'selected':'' ?>><?= e($l) ?></option><?php endforeach;?></select></label><label>Sachverhalt*<textarea name="facts" rows="7" required><?= e($entry['facts']) ?></textarea></label><label>Maßnahmen<textarea name="measures_text" rows="3"><?= e($entry['measures_text']??'') ?></textarea></label><label>Ergebnis<textarea name="result_text" rows="3"><?= e($entry['result_text']??'') ?></textarea></label><button class="button primary" type="submit">Nachtrag speichern</button></form></div><?php endif;?>

<?php if(can('system.trash.manage')&&can('dutybook.delete')):?><div class="panel"><h2>Administration</h2><p>Dieser Dienstbucheintrag kann in den zentralen Papierkorb verschoben und dort wiederhergestellt oder endgültig gelöscht werden.</p><form method="post" action="<?= e(url('admin/trash/dutybook/'.$entry['id'].'/move')) ?>" data-confirm="Dienstbucheintrag wirklich in den Papierkorb verschieben?"><?= csrf_field() ?><button class="button danger" type="submit">In Papierkorb verschieben</button></form></div><?php endif;?>
