<?php $title='Wertsache auslagern'; ?>
<div class="page-header split"><div><p class="eyebrow">Wertsachen · Verwahrnr. <?= e(str_pad((string)$record['custody_number'],4,'0',STR_PAD_LEFT)) ?></p><h1>Vollständige Auslagerung</h1><p>Teilentnahmen sind nicht zulässig. Der gesamte Vorgang wird in einem Schritt abgeschlossen.</p></div><a class="button ghost" href="<?= e(url('valuables/'.$record['id'])) ?>">Zurück</a></div>
<div class="notice warning"><strong>Vor Abschluss prüfen:</strong> <?= e($record['first_name'].' '.$record['last_name']) ?> · <?= count($record['containers']) ?> Behältnis(se). Nach Abschluss kann der Vorgang nicht reaktiviert werden.</div>
<form method="post" action="<?= e(url('valuables/'.$record['id'].'/release')) ?>" class="panel stack-form"><?= csrf_field() ?>
<div class="table-wrap"><table><thead><tr><th>Pos.</th><th>Typ</th><th>Lagerort</th><th>Kassette</th><th>Siegel</th></tr></thead><tbody><?php foreach($record['containers'] as $c):?><tr><td><?= (int)$c['position_number'] ?></td><td><?= e($c['container_type']) ?></td><td><?= e($c['storage_label']) ?></td><td><?= $c['cassette_number']?'Kassette '.(int)$c['cassette_number']:'–' ?></td><td><?= $c['cassette_id']?'L '.$c['seal_left'].' / R '.$c['seal_right']:'–' ?></td></tr><?php endforeach;?></tbody></table></div>
<?php foreach($record['containers'] as $c):if(!$c['cassette_id'])continue;?><div class="seal-check"><h3>Kassette <?= (int)$c['cassette_number'] ?></h3>
<?php foreach(['left'=>'links','right'=>'rechts'] as $side=>$label):?><div class="seal-side-grid"><div><small>Siegel <?= e($label) ?></small><strong><?= e($c['seal_'.$side]) ?></strong></div><label>Nummer stimmt?*<select name="seal_checks[<?= (int)$c['id'] ?>][<?= e($side) ?>_matches]" required><option value="">Bitte wählen …</option><option value="1">Ja</option><option value="0">Nein</option></select></label><label>Zustand*<select name="seal_checks[<?= (int)$c['id'] ?>][<?= e($side) ?>_condition]" required><option value="">Bitte wählen …</option><option value="intact">Intakt</option><option value="damaged">Beschädigt</option><option value="missing">Fehlt</option></select></label><label>Tatsächlich vorgefunden<input inputmode="numeric" name="seal_checks[<?= (int)$c['id'] ?>][<?= e($side) ?>_actual]" placeholder="bei Abweichung"></label><label style="grid-column:2/-1">Begründung bei Abweichung<input name="seal_checks[<?= (int)$c['id'] ?>][<?= e($side) ?>_reason]"></label></div><?php endforeach;?></div><?php endforeach;?>
<div class="form-grid"><label>Auslagerung Datum/Uhrzeit*<input type="datetime-local" name="released_at" required value="<?= e(str_replace(' ','T',substr(date('Y-m-d H:i:s'),0,16))) ?>"></label><label>Ausgabe an betroffene Person?*<select name="receiver_is_subject" data-receiver-subject required><option value="1">Ja</option><option value="0">Nein</option></select></label></div>
<div class="form-grid" data-foreign-receiver hidden><label>Empfängertyp*<select name="receiver_type"><option value="">Bitte wählen …</option><option value="patient">Patient</option><option value="relative">Angehöriger</option><option value="care">Pflege</option><option value="police">Polizei</option><option value="authorized">Bevollmächtigter</option><option value="other">Sonstige</option></select></label><label>Name*<input name="receiver_name"></label><label class="span-2">Grund der Fremdausgabe*<textarea name="receiver_reason"></textarea></label><label class="span-2">Organisation / Bereich<input name="receiver_organization"></label></div>
<label>Bemerkung Auslagerung<textarea name="release_note"></textarea></label>
<label class="check-row"><input type="checkbox" name="release_confirmed" value="1" required><span><strong>Ich bestätige die vollständige Übergabe aller zu diesem Vorgang gehörenden Wertsachen.</strong></span></label>
<button class="button danger" type="submit">Vollständige Auslagerung abschließen</button>
</form>
