<?php $title='Wertsachensuche'; ?>
<div class="page-header split"><div><p class="eyebrow">Wertsachen</p><h1>Suche</h1><p>Aktuell eingelagerte Vorgänge des aktiven Standorts durchsuchen.</p></div><?php if(can('valuables.archive')):?><a class="button ghost" href="<?= e(url('valuables/archive')) ?>">Archiv öffnen</a><?php endif;?></div>
<div class="panel"><form method="get" action="<?= e(url('valuables/search')) ?>" class="form-grid">
<label>Verwahrnummer<input name="custody_number" inputmode="numeric" value="<?= e($filters['custody_number']) ?>"></label><div class="detail-item"><small>Status</small><strong>Eingelagert</strong></div>
<label>Vorname<input name="first_name" value="<?= e($filters['first_name']) ?>"></label><label>Nachname<input name="last_name" value="<?= e($filters['last_name']) ?>"></label><label>Geburtsdatum<input type="date" name="birth_date" value="<?= e($filters['birth_date']) ?>"></label><label>Interne Kennung<input name="internal_identifier" value="<?= e($filters['internal_identifier']) ?>"></label>
<label>Kassettennummer<input type="number" min="1" max="100" name="cassette_number" value="<?= e($filters['cassette_number']) ?>"></label><label>Siegelnummer<input inputmode="numeric" name="seal" value="<?= e($filters['seal']) ?>"></label><label>Lagerort<select name="storage_location_id"><option value="">Alle</option><?php foreach($storage as $s):?><option value="<?= (int)$s['id'] ?>" <?= (int)$filters['storage_location_id']===(int)$s['id']?'selected':'' ?>><?= e($s['label']) ?></option><?php endforeach;?></select></label>
<label>Einlagerung von<input type="date" name="stored_from" value="<?= e($filters['stored_from']) ?>"></label><label>Einlagerung bis<input type="date" name="stored_to" value="<?= e($filters['stored_to']) ?>"></label>
<div class="span-2 form-actions"><button class="button primary" type="submit">Suchen</button></div></form></div>
<div class="panel"><div class="table-wrap"><table><thead><tr><th>Verwahrnr.</th><th>Person</th><th>Status</th><th>Einlagerung</th><th>Auslagerung</th><th>Behältnisse</th><th></th></tr></thead><tbody><?php foreach($result['items'] as $r):?><tr><td><strong><?= e(str_pad((string)$r['custody_number'],4,'0',STR_PAD_LEFT)) ?></strong></td><td><?= e($r['last_name'].', '.$r['first_name']) ?><small class="table-sub"><?= e((new DateTimeImmutable($r['birth_date']))->format('d.m.Y')) ?></small></td><td><span class="badge <?= $r['status']==='stored'?'active':'neutral' ?>"><?= $r['status']==='stored'?'Eingelagert':'Ausgelagert' ?></span></td><td><?= e(format_datetime($r['stored_at'])) ?></td><td><?= e(format_datetime($r['released_at'])) ?></td><td><?= (int)$r['container_count'] ?></td><td><a class="button ghost compact" href="<?= e(url('valuables/'.$r['id'])) ?>">Öffnen</a></td></tr><?php endforeach;?><?php if($result['items']===[]):?><tr><td colspan="7" class="empty">Keine Treffer.</td></tr><?php endif;?></tbody></table></div><div class="pagination"><span><?= (int)$result['total'] ?> Treffer</span><span>Seite <?= (int)$result['page'] ?> / <?= (int)$result['pages'] ?></span></div></div>
