<?php
$title='Wertsache '.str_pad((string)$record['custody_number'],4,'0',STR_PAD_LEFT);
$typeLabels=['cassette'=>'Kassette','bag'=>'Tüte','sack'=>'Sack','case'=>'Koffer','pocket'=>'Tasche','other'=>'Sonstiges'];
?>
<div class="page-header split"><div><p class="eyebrow">Wertsachen · Verwahrnr. <?= e(str_pad((string)$record['custody_number'],4,'0',STR_PAD_LEFT)) ?></p><h1><?= e($record['last_name'].', '.$record['first_name']) ?></h1><p><?= $record['status']==='stored'?'Aktuell eingelagert':'Vollständig ausgelagert' ?></p></div><div class="inline-actions"><a class="button ghost" href="<?= e(url('valuables')) ?>">Übersicht</a><?php if($record['status']==='stored'&&can('valuables.release')):?><a class="button primary" href="<?= e(url('valuables/'.$record['id'].'/release')) ?>">Vollständig auslagern</a><?php endif;?></div></div>
<?php if($record['correction_parent_id']):?><div class="notice info">Dieser Vorgang ist eine Korrekturfolge zu Verwahrnr. <?= e(str_pad((string)$record['correction_parent_number'],4,'0',STR_PAD_LEFT)) ?>.</div><?php endif;?>
<div class="panel"><div class="detail-grid">
<div class="detail-item"><small>Verwahrnummer</small><strong><?= e(str_pad((string)$record['custody_number'],4,'0',STR_PAD_LEFT)) ?></strong></div><div class="detail-item"><small>Geburtsdatum</small><strong><?= e((new DateTimeImmutable($record['birth_date']))->format('d.m.Y')) ?></strong></div><div class="detail-item"><small>Interne Kennung</small><strong><?= e($record['internal_identifier']??'–') ?></strong></div>
<div class="detail-item"><small>Eingelagert</small><strong><?= e(format_datetime($record['stored_at'])) ?></strong></div><div class="detail-item"><small>Einlagernder Mitarbeiter</small><strong><?= e($record['stored_by_name']??'–') ?></strong></div><div class="detail-item"><small>Übergeben durch</small><strong><?= e($record['handed_over_by_name']) ?></strong><small><?= e($record['handed_over_by_organization']??'') ?></small></div>
<?php if($record['status']==='released'):?><div class="detail-item"><small>Ausgelagert</small><strong><?= e(format_datetime($record['released_at'])) ?></strong></div><div class="detail-item"><small>Auslagernder Mitarbeiter</small><strong><?= e($record['released_by_name']??'–') ?></strong></div><div class="detail-item"><small>Empfänger</small><strong><?= e($record['receiver_name']??'–') ?></strong><small><?= e($record['receiver_type']??'') ?></small></div><div class="detail-item"><small>Aufbewahrung bis</small><strong><?= e($retentionUntil?->format('d.m.Y')??'–') ?></strong><small><?= $retentionUntil&&$retentionUntil<=new DateTimeImmutable()?'Frist abgelaufen · manuelle Prüfung möglich':'Aufbewahrungsfrist läuft' ?></small></div><?php endif;?>
</div>
<h3 class="section-title">Behältnisse</h3><div class="table-wrap"><table><thead><tr><th>Pos.</th><th>Typ</th><th>Beschreibung</th><th>Lagerort</th><th>Kassette</th><th>Siegel links</th><th>Siegel rechts</th></tr></thead><tbody><?php foreach($record['containers'] as $c):?><tr><td><?= (int)$c['position_number'] ?></td><td><?= e($typeLabels[$c['container_type']]??$c['container_type']) ?></td><td><?= e($c['description']??'–') ?></td><td><?= e($c['storage_label']) ?></td><td><?= $c['cassette_number']?'Kassette '.(int)$c['cassette_number']:'–' ?></td><td><?= e($c['seal_left']??'–') ?></td><td><?= e($c['seal_right']??'–') ?></td></tr><?php endforeach;?></tbody></table></div>
<?php if($record['status']==='released'):?><h3 class="section-title">Siegelprüfung bei Auslagerung</h3><?php foreach($record['containers'] as $c):if(!$c['cassette_id'])continue;?><div class="seal-check"><strong>Kassette <?= (int)$c['cassette_number'] ?></strong><div class="detail-grid"><div class="detail-item"><small>Links · hinterlegt <?= e($c['seal_left']) ?></small><strong><?= $c['seal_left_matches']?'Nummer stimmt':'Abweichung' ?> · <?= e($c['seal_left_condition']??'–') ?></strong><?php if(!$c['seal_left_matches']):?><small>Vorgefunden: <?= e($c['seal_left_actual']??'fehlt') ?> · <?= e($c['seal_left_reason']??'') ?></small><?php endif;?></div><div class="detail-item"><small>Rechts · hinterlegt <?= e($c['seal_right']) ?></small><strong><?= $c['seal_right_matches']?'Nummer stimmt':'Abweichung' ?> · <?= e($c['seal_right_condition']??'–') ?></strong><?php if(!$c['seal_right_matches']):?><small>Vorgefunden: <?= e($c['seal_right_actual']??'fehlt') ?> · <?= e($c['seal_right_reason']??'') ?></small><?php endif;?></div></div></div><?php endforeach;?><?php endif;?>
<?php if($record['storage_note']):?><h3 class="section-title">Bemerkung Einlagerung</h3><div class="prose"><?= e($record['storage_note']) ?></div><?php endif;?><?php if($record['release_note']):?><h3 class="section-title">Bemerkung Auslagerung</h3><div class="prose"><?= e($record['release_note']) ?></div><?php endif;?>
<?php if($record['attachments']):?><h3 class="section-title">Anhänge</h3><div class="timeline-list"><?php foreach($record['attachments'] as $a):?><div class="timeline-item"><a href="<?= e(url('attachments/'.$a['id'].'/download')) ?>"><strong><?= e($a['original_name']) ?></strong></a><small class="table-sub"><?= e(format_datetime($a['uploaded_at'])) ?> · <?= e($a['uploader_name']??'') ?></small></div><?php endforeach;?></div><?php endif;?>
</div>
<div class="two-col"><div class="panel"><h2>Interne Notizen / Nachträge</h2><?php if($record['notes']):?><div class="timeline-list"><?php foreach($record['notes'] as $n):?><div class="timeline-item"><div class="prose"><?= e($n['note_text']) ?></div><small class="table-sub"><?= e($n['user_name']??'') ?> · <?= e(format_datetime($n['created_at'])) ?></small></div><?php endforeach;?></div><?php else:?><p class="muted">Noch keine internen Notizen.</p><?php endif;?><?php if(can('valuables.add_note')):?><form method="post" action="<?= e(url('valuables/'.$record['id'].'/note')) ?>" class="stack-form"><?= csrf_field() ?><label>Neue interne Notiz<textarea name="note_text" required></textarea></label><button class="button secondary" type="submit">Notiz hinzufügen</button></form><?php endif;?></div>
<div class="panel"><h2>Änderungshistorie</h2><?php if($record['history']):?><div class="timeline-list"><?php foreach($record['history'] as $h):?><div class="timeline-item"><strong><?= e($h['field_name']) ?></strong><small class="table-sub"><?= e($h['user_name']??'') ?> · <?= e(format_datetime($h['changed_at'])) ?><?= $h['change_reason']?' · '.e($h['change_reason']):'' ?></small></div><?php endforeach;?></div><?php else:?><p class="muted">Keine nachträglichen Änderungen protokolliert.</p><?php endif;?></div></div>
<?php if($record['status']==='released'&&can('valuables.store')):?><div class="panel"><h2>Fehlerhafte Auslagerung korrigieren</h2><p>Der abgeschlossene Vorgang wird nicht reaktiviert. Falls die Wertsache tatsächlich noch vorhanden ist, wird ein neuer Vorgang mit neuer Verwahrnummer erstellt und als Korrekturfolge verknüpft.</p><a class="button secondary" href="<?= e(url('valuables/'.$record['id'].'/correction')) ?>">Neuen Korrekturvorgang anlegen</a></div><?php endif;?>

<?php if($record['status']==='released'&&can('system.trash.manage')&&can('valuables.delete')):?><div class="panel"><h2>Administration</h2><p>Nur vollständig ausgelagerte Vorgänge dürfen in den Papierkorb verschoben werden. Bereits verwendete Siegel bleiben auch nach endgültiger Löschung dauerhaft gesperrt.</p><form method="post" action="<?= e(url('admin/trash/valuables/'.$record['id'].'/move')) ?>" data-confirm="Wertsachenvorgang wirklich in den Papierkorb verschieben?"><?= csrf_field() ?><button class="button danger" type="submit">In Papierkorb verschieben</button></form></div><?php endif;?>
