<?php
$editing=is_array($report);$title=$editing?'Sonderbericht bearbeiten':'Sonderbericht erstellen';
$selectedType=(int)old('report_type_id',$report['report_type_id']??0);$oldDyn=(array)old('dynamic',[]);
$staffSelected=array_map('intval',(array)old('staff_ids',$editing?array_column($report['staff'],'id'):($prefill?array_column($prefill['staff'],'id'):[])));
$people=(array)old('people',$editing?$report['people']:($prefill?$prefill['people']:[]));$witnesses=(array)old('witnesses',$editing?$report['witnesses']:[]);
$external=(array)old('external',$editing?$report['external']:($prefill?$prefill['external']:[]));$force=(array)old('force_actions',$editing?$report['force_actions']:[]);
$inj=(array)old('injury',$editing?($report['injury']??[]):[]);
$start=old('incident_started_at',$report['incident_started_at']??$prefill['occurred_at']??date('Y-m-d H:i:s'));
$source=(int)old('source_dutybook_entry_id',$report['source_dutybook_entry_id']??$prefill['id']??0);
?>
<div class="page-header split"><div><p class="eyebrow">Sonderberichte</p><h1><?= e($title) ?></h1><p>Dynamisches Formular mit beteiligten Personen, Zeugen, medizinischen Maßnahmen und Anlagen.</p></div><a class="button ghost" href="<?= e($editing?url('special-reports/'.$report['id']):url('special-reports')) ?>">Zurück</a></div>
<?php if(!empty($autosave)): ?><div class="notice info"><strong>Automatischer Entwurf gefunden.</strong> Gespeichert <?= e(format_datetime($autosave['updated_at'])) ?>. <a href="<?= e(($editing?url('special-reports/'.$report['id'].'/edit'):url('special-reports/create')).'?restore_autosave=1') ?>">Wiederherstellen</a><form method="post" action="<?= e(url('autosave/discard')) ?>" class="inline-form"><?= csrf_field() ?><input type="hidden" name="module" value="special_report"><input type="hidden" name="context_key" value="<?= e($autosaveContext) ?>"><input type="hidden" name="redirect_to" value="<?= e($editing?url('special-reports/'.$report['id'].'/edit'):url('special-reports/create')) ?>"><button class="button ghost compact" type="submit">Verwerfen</button></form></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" action="<?= e($editing?url('special-reports/'.$report['id']):url('special-reports')) ?>" class="panel form-grid" data-unsaved-warning data-autosave data-autosave-module="special_report" data-autosave-context="<?= e($autosaveContext) ?>" data-autosave-url="<?= e(url('autosave')) ?>">
<?= csrf_field() ?><input type="hidden" name="source_dutybook_entry_id" value="<?= $source ?>">
<label>Einsatzart*<select name="report_type_id" required data-event-type-select><option value="">Bitte wählen …</option><?php foreach($types as $t):?><option value="<?= (int)$t['id'] ?>" data-force="<?= $t['force_section_enabled']?1:0 ?>" <?= $selectedType===(int)$t['id']?'selected':'' ?>><?= e($t['name']) ?></option><?php endforeach;?></select></label>
<label>Einsatzdatum*<input type="date" name="incident_date" required value="<?= e(old('incident_date',$report['incident_date']??($prefill?substr($prefill['occurred_at'],0,10):date('Y-m-d')))) ?>"></label>
<label>Beginn*<input type="datetime-local" name="incident_started_at" required value="<?= e(str_replace(' ','T',substr((string)$start,0,16))) ?>"></label>
<label>Ende<input type="datetime-local" name="incident_ended_at" value="<?= e(($v=old('incident_ended_at',$report['incident_ended_at']??''))?str_replace(' ','T',substr((string)$v,0,16)):'') ?>"></label>
<label>Ort<select name="place_id"><option value="">Keine feste Auswahl</option><?php foreach($places as $p):?><option value="<?= (int)$p['id'] ?>" <?= (int)old('place_id',$report['place_id']??$prefill['place_id']??0)===(int)$p['id']?'selected':'' ?>><?= e(($p['parent_name']?$p['parent_name'].' / ':'').$p['name']) ?></option><?php endforeach;?></select></label>
<label>Genauer Einsatzort<input name="place_free_text" value="<?= e(old('place_free_text',$report['place_free_text']??$prefill['place_free_text']??'')) ?>"></label>
<div class="span-2"><?php foreach($dynamicByType as $typeId=>$fields):?><div class="form-grid dynamic-group" data-dynamic-event="<?= (int)$typeId ?>"><?php foreach($fields as $f):$value=$oldDyn[$f['id']]??($editing&&isset($report['dynamic_values'][$f['id']])?$report['dynamic_values'][$f['id']]['value']:'');$name='dynamic['.(int)$f['id'].']';?><label><?= e($f['label']) ?><?= $f['required']?'*':'' ?><?php if($f['field_type']==='textarea'):?><textarea name="<?= e($name) ?>" <?= $f['required']?'required':'' ?>><?= e($value) ?></textarea><?php elseif($f['field_type']==='select'):?><select name="<?= e($name) ?>" <?= $f['required']?'required':'' ?>><option value="">Bitte wählen …</option><?php foreach($f['options'] as $o):?><option value="<?= e($o) ?>" <?= (string)$value===(string)$o?'selected':'' ?>><?= e($o) ?></option><?php endforeach;?></select><?php elseif($f['field_type']==='multiselect'):?><select multiple name="<?= e($name) ?>[]" <?= $f['required']?'required':'' ?>><?php foreach($f['options'] as $o):?><option value="<?= e($o) ?>" <?= in_array((string)$o,(array)$value,true)?'selected':'' ?>><?= e($o) ?></option><?php endforeach;?></select><?php elseif($f['field_type']==='checkbox'):?><span class="check-row"><input type="checkbox" name="<?= e($name) ?>" value="1" <?= $value?'checked':'' ?>><span>Ja</span></span><?php elseif($f['field_type']==='yesno'):?><select name="<?= e($name) ?>" <?= $f['required']?'required':'' ?>><option value="">Bitte wählen …</option><option value="ja" <?= $value==='ja'?'selected':'' ?>>Ja</option><option value="nein" <?= $value==='nein'?'selected':'' ?>>Nein</option></select><?php else:?><input type="<?= e(match($f['field_type']){'number'=>'number','date'=>'date','time'=>'time','datetime'=>'datetime-local',default=>'text'}) ?>" name="<?= e($name) ?>" value="<?= e($value) ?>" <?= $f['required']?'required':'' ?>><?php endif;?></label><?php endforeach;?></div><?php endforeach;?></div>
<label class="span-2">Sachverhalt*<textarea name="facts" rows="10" required><?= e(old('facts',$report['facts']??$prefill['facts']??'')) ?></textarea></label>

<fieldset class="span-2 checkbox-panel"><legend>Beteiligte Mitarbeiter</legend><div class="checkbox-stack"><?php foreach($users as $u):?><label class="check-row"><input type="checkbox" name="staff_ids[]" value="<?= (int)$u['id'] ?>" <?= in_array((int)$u['id'],$staffSelected,true)?'checked':'' ?>><span><?= e($u['last_name'].', '.$u['first_name']) ?></span></label><?php endforeach;?></div></fieldset>

<div class="span-2"><div class="section-title">Beteiligte Personen</div><div class="repeat-list" id="sr-people"><?php foreach($people as $i=>$p):?><div class="repeat-row people" data-repeat-row><label>Rolle<select name="people[<?= $i ?>][role_id]"><option value="">–</option><?php foreach($roles as $r):?><option value="<?= (int)$r['id'] ?>" <?= (int)($p['role_id']??0)===(int)$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach;?></select></label><label>Vorname<input name="people[<?= $i ?>][first_name]" value="<?= e($p['first_name']??'') ?>"></label><label>Nachname<input name="people[<?= $i ?>][last_name]" value="<?= e($p['last_name']??'') ?>"></label><label>Geburtsdatum<input type="date" name="people[<?= $i ?>][birth_date]" value="<?= e($p['birth_date']??'') ?>"></label><label>Personentyp<input name="people[<?= $i ?>][person_type]" value="<?= e($p['person_type']??'') ?>"></label><label>Station/Bereich<input name="people[<?= $i ?>][area]" value="<?= e($p['area']??'') ?>"></label><label>Interne Kennung<input name="people[<?= $i ?>][internal_identifier]" value="<?= e($p['internal_identifier']??'') ?>"></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div><?php endforeach;?><template><div class="repeat-row people" data-repeat-row><label>Rolle<select name="people[__INDEX__][role_id]"><option value="">–</option><?php foreach($roles as $r):?><option value="<?= (int)$r['id'] ?>"><?= e($r['name']) ?></option><?php endforeach;?></select></label><label>Vorname<input name="people[__INDEX__][first_name]"></label><label>Nachname<input name="people[__INDEX__][last_name]"></label><label>Geburtsdatum<input type="date" name="people[__INDEX__][birth_date]"></label><label>Personentyp<input name="people[__INDEX__][person_type]"></label><label>Station/Bereich<input name="people[__INDEX__][area]"></label><label>Interne Kennung<input name="people[__INDEX__][internal_identifier]"></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div></template></div><button type="button" class="button secondary" data-repeat-add="#sr-people">+ Person</button></div>

<div class="span-2"><div class="section-title">Zeugen</div><div class="repeat-list" id="sr-witnesses"><?php foreach($witnesses as $i=>$w):?><div class="repeat-row external" data-repeat-row><label>Name*<input name="witnesses[<?= $i ?>][name]" value="<?= e($w['name']??'') ?>"></label><label>Kontaktdaten<input name="witnesses[<?= $i ?>][contact_details]" value="<?= e($w['contact_details']??'') ?>"></label><label>Aussage / Zusammenfassung<textarea name="witnesses[<?= $i ?>][statement_summary]"><?= e($w['statement_summary']??'') ?></textarea></label><label class="check-row"><input type="checkbox" name="witnesses[<?= $i ?>][written_statement]" value="1" <?= !empty($w['written_statement'])?'checked':'' ?>><span>schriftliche Aussage vorhanden</span></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div><?php endforeach;?><template><div class="repeat-row external" data-repeat-row><label>Name*<input name="witnesses[__INDEX__][name]"></label><label>Kontaktdaten<input name="witnesses[__INDEX__][contact_details]"></label><label>Aussage / Zusammenfassung<textarea name="witnesses[__INDEX__][statement_summary]"></textarea></label><label class="check-row"><input type="checkbox" name="witnesses[__INDEX__][written_statement]" value="1"><span>schriftliche Aussage vorhanden</span></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div></template></div><button type="button" class="button secondary" data-repeat-add="#sr-witnesses">+ Zeuge</button></div>

<label class="span-2">Maßnahmen<textarea name="measures_text" rows="5"><?= e(old('measures_text',$report['measures_text']??$prefill['measures_text']??'')) ?></textarea></label><label class="span-2">Ergebnis<textarea name="result_text" rows="4"><?= e(old('result_text',$report['result_text']??$prefill['result_text']??'')) ?></textarea></label>

<fieldset class="span-2 checkbox-panel"><legend>Verletzungen / medizinische Maßnahmen</legend><label class="check-row"><input type="checkbox" name="injury[injury_present]" value="1" <?= !empty($inj['injury_present'])?'checked':'' ?>><span>Verletzung vorhanden</span></label><div class="form-grid"><label>Art/Beschreibung<textarea name="injury[description]"><?= e($inj['description']??'') ?></textarea></label><label>Medizinische Versorgung<textarea name="injury[medical_care]"><?= e($inj['medical_care']??'') ?></textarea></label><label>Behandelnde Stelle<input name="injury[treating_entity]" value="<?= e($inj['treating_entity']??'') ?>"></label><label>Zeitpunkt<input type="datetime-local" name="injury[treated_at]" value="<?= e(!empty($inj['treated_at'])?str_replace(' ','T',substr($inj['treated_at'],0,16)):'') ?>"></label></div></fieldset>

<div class="span-2" data-force-section hidden><div class="section-title">Zwangsmaßnahmen / Fixierungen / körperliches Eingreifen</div><div class="repeat-list" id="sr-force"><?php foreach($force as $i=>$f):?><div class="panel" data-repeat-row><div class="form-grid"><label>Art der Maßnahme<input name="force_actions[<?= $i ?>][action_type]" value="<?= e($f['action_type']??'') ?>"></label><label>Beginn<input type="datetime-local" name="force_actions[<?= $i ?>][started_at]" value="<?= e(!empty($f['started_at'])?str_replace(' ','T',substr($f['started_at'],0,16)):'') ?>"></label><label>Ende<input type="datetime-local" name="force_actions[<?= $i ?>][ended_at]" value="<?= e(!empty($f['ended_at'])?str_replace(' ','T',substr($f['ended_at'],0,16)):'') ?>"></label><label>Begründung<textarea name="force_actions[<?= $i ?>][justification]"><?= e($f['justification']??'') ?></textarea></label><label>Ergebnis<textarea name="force_actions[<?= $i ?>][result_text]"><?= e($f['result_text']??'') ?></textarea></label></div><div class="checkbox-stack"><?php $fs=array_map('intval',array_column($f['staff']??[],'id'));foreach($users as $u):?><label class="check-row"><input type="checkbox" name="force_actions[<?= $i ?>][staff_ids][]" value="<?= (int)$u['id'] ?>" <?= in_array((int)$u['id'],$fs,true)?'checked':'' ?>><span><?= e($u['last_name'].', '.$u['first_name']) ?></span></label><?php endforeach;?></div><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div><?php endforeach;?><template><div class="panel" data-repeat-row><div class="form-grid"><label>Art der Maßnahme<input name="force_actions[__INDEX__][action_type]"></label><label>Beginn<input type="datetime-local" name="force_actions[__INDEX__][started_at]"></label><label>Ende<input type="datetime-local" name="force_actions[__INDEX__][ended_at]"></label><label>Begründung<textarea name="force_actions[__INDEX__][justification]"></textarea></label><label>Ergebnis<textarea name="force_actions[__INDEX__][result_text]"></textarea></label></div><div class="checkbox-stack"><?php foreach($users as $u):?><label class="check-row"><input type="checkbox" name="force_actions[__INDEX__][staff_ids][]" value="<?= (int)$u['id'] ?>"><span><?= e($u['last_name'].', '.$u['first_name']) ?></span></label><?php endforeach;?></div><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div></template></div><button type="button" class="button secondary" data-repeat-add="#sr-force">+ Zwangsmaßnahme</button></div>

<div class="span-2"><div class="section-title">Externe Stellen</div><div class="repeat-list" id="sr-external"><?php foreach($external as $i=>$x):?><div class="repeat-row external" data-repeat-row><label>Organisation<select name="external[<?= $i ?>][organization_id]"><option value="">Freitext</option><?php foreach($externalOrganizations as $o):?><option value="<?= (int)$o['id'] ?>" <?= (int)($x['organization_id']??0)===(int)$o['id']?'selected':'' ?>><?= e($o['organization_type'].' · '.$o['name']) ?></option><?php endforeach;?></select></label><label>Organisation Freitext<input name="external[<?= $i ?>][organization_name]" value="<?= e($x['organization_name']??'') ?>"></label><label>Ansprechpartner<input name="external[<?= $i ?>][contact_name]" value="<?= e($x['contact_name']??'') ?>"></label><label>Verständigt<input type="datetime-local" name="external[<?= $i ?>][notified_at]" value="<?= e(!empty($x['notified_at'])?str_replace(' ','T',substr($x['notified_at'],0,16)):'') ?>"></label><label>Vorgangsnummer<input name="external[<?= $i ?>][reference_number]" value="<?= e($x['reference_number']??'') ?>"></label><label>Rückmeldung<input name="external[<?= $i ?>][feedback]" value="<?= e($x['feedback']??'') ?>"></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div><?php endforeach;?><template><div class="repeat-row external" data-repeat-row><label>Organisation<select name="external[__INDEX__][organization_id]"><option value="">Freitext</option><?php foreach($externalOrganizations as $o):?><option value="<?= (int)$o['id'] ?>"><?= e($o['organization_type'].' · '.$o['name']) ?></option><?php endforeach;?></select></label><label>Organisation Freitext<input name="external[__INDEX__][organization_name]"></label><label>Ansprechpartner<input name="external[__INDEX__][contact_name]"></label><label>Verständigt<input type="datetime-local" name="external[__INDEX__][notified_at]"></label><label>Vorgangsnummer<input name="external[__INDEX__][reference_number]"></label><label>Rückmeldung<input name="external[__INDEX__][feedback]"></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div></template></div><button type="button" class="button secondary" data-repeat-add="#sr-external">+ Externe Stelle</button></div>

<label class="span-2">Anlagen<input type="file" name="attachments[]" multiple accept=".jpg,.jpeg,.png,.pdf,.docx"></label>
<div class="span-2 form-actions"><button class="button secondary" type="submit" name="status" value="draft">Als Entwurf speichern</button><button class="button primary" type="submit" name="status" value="in_progress">In Bearbeitung speichern</button></div>
</form>
