<?php $title='Sonderbericht '.$service->displayNumber($report);$labels=['draft'=>'Entwurf','in_progress'=>'In Bearbeitung','revision_required'=>'Nachbearbeitung erforderlich','completed'=>'Abgeschlossen / ungeprüft','reviewed'=>'Geprüft']; ?>
<div class="page-header split"><div><p class="eyebrow">Sonderbericht · <?= e($service->displayNumber($report)) ?></p><h1><?= e($report['report_type_name']) ?></h1><p><?= e($labels[$report['status']]??$report['status']) ?> · Ersteller <?= e($report['creator_name']??'–') ?></p></div><div class="inline-actions"><a class="button ghost" href="<?= e(url('special-reports')) ?>">Übersicht</a><?php if(in_array($report['status'],['draft','in_progress','revision_required'],true)&&can('special_reports.create')):?><a class="button primary" href="<?= e(url('special-reports/'.$report['id'].'/edit')) ?>">Bearbeiten</a><?php endif;?></div></div>
<div class="toolbar"><?php if(can('special_reports.export')):?><a class="button ghost" href="<?= e(url('special-reports/'.$report['id'].'/pdf')) ?>">PDF</a><a class="button ghost" href="<?= e(url('special-reports/'.$report['id'].'/docx')) ?>">DOCX</a><a class="button ghost" target="_blank" href="<?= e(url('special-reports/'.$report['id'].'/print')) ?>">Druckansicht</a><?php endif;?></div>
<div class="panel"><div class="detail-grid"><div class="detail-item"><small>Nummer</small><strong><?= e($service->displayNumber($report)) ?></strong></div><div class="detail-item"><small>Einsatzdatum</small><strong><?= e((new DateTimeImmutable($report['incident_date']))->format('d.m.Y')) ?></strong></div><div class="detail-item"><small>Status</small><span class="badge status-<?= e($report['status']) ?>"><?= e($labels[$report['status']]??$report['status']) ?></span></div><div class="detail-item"><small>Beginn</small><strong><?= e(format_datetime($report['incident_started_at'])) ?></strong></div><div class="detail-item"><small>Ende</small><strong><?= e(format_datetime($report['incident_ended_at'])) ?></strong></div><div class="detail-item"><small>Ort</small><strong><?= e(trim(($report['place_name']??'').' '.($report['place_free_text']??''))?:'–') ?></strong></div><div class="detail-item wide"><small>Sachverhalt</small><div class="prose"><?= e($report['facts']) ?></div></div><div class="detail-item wide"><small>Maßnahmen</small><div class="prose"><?= e($report['measures_text']??'–') ?></div></div><div class="detail-item wide"><small>Ergebnis</small><div class="prose"><?= e($report['result_text']??'–') ?></div></div></div>
<?php foreach($dynamicSections as $section=>$values):?><h3 class="section-title"><?= e($section) ?></h3><div class="detail-grid"><?php foreach($values as $v):?><div class="detail-item"><small><?= e($v['label']) ?></small><strong><?= e(is_array($v['value'])?implode(', ',$v['value']):(is_bool($v['value'])?($v['value']?'Ja':'Nein'):$v['value'])) ?></strong></div><?php endforeach;?></div><?php endforeach;?>
<?php if($report['people']):?><h3 class="section-title">Beteiligte Personen</h3><div class="table-wrap"><table><thead><tr><th>Rolle</th><th>Name</th><th>Geburtsdatum</th><th>Bereich</th><th>Kennung</th></tr></thead><tbody><?php foreach($report['people'] as $p):?><tr><td><?= e($p['role_name']??$p['person_type']??'–') ?></td><td><?= e(trim(($p['first_name']??'').' '.($p['last_name']??''))) ?></td><td><?= e($p['birth_date']??'–') ?></td><td><?= e($p['area']??'–') ?></td><td><?= e($p['internal_identifier']??'–') ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if($report['witnesses']):?><h3 class="section-title">Zeugen</h3><div class="table-wrap"><table><thead><tr><th>Name</th><th>Kontakt</th><th>Aussage</th><th>Schriftlich</th></tr></thead><tbody><?php foreach($report['witnesses'] as $w):?><tr><td><?= e($w['name']) ?></td><td><?= e($w['contact_details']??'–') ?></td><td><?= e($w['statement_summary']??'–') ?></td><td><?= $w['written_statement']?'Ja':'Nein' ?><?php if($w['attachment_id']):?> · <a href="<?= e(url('attachments/'.$w['attachment_id'].'/download')) ?>">Anlage</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if($report['staff']):?><h3 class="section-title">Beteiligte Mitarbeiter</h3><p><?= e(implode(', ',array_map(fn($u)=>$u['first_name'].' '.$u['last_name'],$report['staff']))) ?></p><?php endif;?>
<?php if($report['injury']):?><h3 class="section-title">Verletzungen / medizinische Maßnahmen</h3><div class="detail-grid"><div class="detail-item"><small>Verletzung</small><strong><?= $report['injury']['injury_present']?'Ja':'Nein' ?></strong></div><div class="detail-item"><small>Behandelnde Stelle</small><strong><?= e($report['injury']['treating_entity']??'–') ?></strong></div><div class="detail-item"><small>Zeitpunkt</small><strong><?= e(format_datetime($report['injury']['treated_at'])) ?></strong></div><div class="detail-item wide"><small>Beschreibung / Versorgung</small><div class="prose"><?= e(trim(($report['injury']['description']??'').' '.($report['injury']['medical_care']??''))?:'–') ?></div></div></div><?php endif;?>
<?php if($report['force_actions']):?><h3 class="section-title">Zwangsmaßnahmen</h3><div class="timeline-list"><?php foreach($report['force_actions'] as $f):?><div class="timeline-item"><strong><?= e($f['action_type']) ?></strong><small class="table-sub"><?= e(format_datetime($f['started_at'])) ?> – <?= e(format_datetime($f['ended_at'])) ?></small><div><?= e($f['justification']??'') ?></div></div><?php endforeach;?></div><?php endif;?>
<?php if($report['external']):?><h3 class="section-title">Externe Stellen</h3><div class="timeline-list"><?php foreach($report['external'] as $x):?><div class="timeline-item"><strong><?= e($x['organization_master_name']??$x['organization_name']??'–') ?></strong><small class="table-sub"><?= e($x['contact_name']??'') ?> · <?= e(format_datetime($x['notified_at'])) ?> · <?= e($x['reference_number']??'') ?></small><div><?= e($x['feedback']??'') ?></div></div><?php endforeach;?></div><?php endif;?>
<?php if($report['attachments']):?><h3 class="section-title">Anlagen</h3><div class="timeline-list"><?php foreach($report['attachments'] as $a):?><div class="timeline-item"><a href="<?= e(url('attachments/'.$a['id'].'/download')) ?>"><strong><?= e($a['original_name']) ?></strong></a><?php if($a['description']):?><div class="prose"><?= e($a['description']) ?></div><?php endif;?><small class="table-sub"><?= e(format_datetime($a['uploaded_at'])) ?> · <?= e($a['uploader_name']??'') ?></small></div><?php endforeach;?></div><?php endif;?>
</div>

<?php if($report['revision_requests']):?><div class="panel"><div class="panel-header"><div><h2>Nachforderungen</h2><p>Einzelne Prüfpunkte aus der Leitungsprüfung.</p></div></div><div class="timeline-list"><?php foreach($report['revision_requests'] as $rr):?><div class="timeline-item"><strong><?= e($rr['request_text']) ?></strong><small class="table-sub"><?= e($rr['creator_name']??'') ?> · <?= e(format_datetime($rr['created_at'])) ?> · <?= $rr['status']==='done'?'Erledigt':'Offen' ?></small><?php if($rr['status']==='open'&&(int)$report['created_by']===(int)\WKS\Core\Auth::id()):?><form method="post" action="<?= e(url('special-reports/'.$report['id'].'/revision/'.$rr['id'].'/done')) ?>"><?= csrf_field() ?><button class="button secondary compact" type="submit">Als erledigt markieren</button></form><?php endif;?></div><?php endforeach;?></div></div><?php endif;?>

<?php if(in_array($report['status'],['draft','in_progress','revision_required'],true)&&can('special_reports.close')):?><div class="panel"><div class="panel-header"><div><h2>Bericht abschließen</h2><p>Mit dem Abschluss bestätigt der Ersteller den Bericht digital. Danach ist er bis zu einer Nachbearbeitungsanforderung gesperrt.</p></div></div><form method="post" action="<?= e(url('special-reports/'.$report['id'].'/complete')) ?>"><?= csrf_field() ?><button class="button primary" type="submit">Bericht digital bestätigen & abschließen</button></form></div><?php endif;?>

<?php if($report['status']==='completed'&&(can('special_reports.review')||can('special_reports.request_revision'))):?><div class="two-col"><?php if(can('special_reports.request_revision')):?><div class="panel"><h2>Nachbearbeitung anfordern</h2><form method="post" action="<?= e(url('special-reports/'.$report['id'].'/review/request')) ?>" class="stack-form"><input type="hidden" name="_token" value="<?= e(\WKS\Core\Csrf::token()) ?>"><div id="revision-repeat" class="repeat-list"><div data-repeat-row><label>Nachforderung 1<textarea name="requests[0]" required></textarea></label></div><template><div data-repeat-row><label>Weitere Nachforderung<textarea name="requests[__INDEX__]" required></textarea></label><button type="button" class="button ghost compact" data-repeat-remove>Entfernen</button></div></template></div><button type="button" class="button secondary" data-repeat-add="#revision-repeat">+ Nachforderung</button><label>Allgemeiner Prüfvermerk<textarea name="review_note"></textarea></label><button class="button danger" type="submit">Nachbearbeitung anfordern</button></form></div><?php endif;?><?php if(can('special_reports.review')):?><div class="panel"><h2>Leitungsprüfung abschließen</h2><form method="post" action="<?= e(url('special-reports/'.$report['id'].'/review/approve')) ?>" class="stack-form"><?= csrf_field() ?><label>Prüfvermerk<textarea name="review_note"></textarea></label><button class="button primary" type="submit">Prüfung digital bestätigen</button></form></div><?php endif;?></div><?php endif;?>

<?php if($report['status']==='reviewed'):?><div class="panel"><div class="panel-header"><div><h2>Versionen</h2><p>Geprüfte und spätere Fassungen bleiben unveränderlich nachvollziehbar.</p></div></div><div class="timeline-list"><?php foreach($report['versions'] as $v):?><div class="timeline-item"><strong>Version <?= (int)$v['version_number'] ?></strong><small class="table-sub"><?= e(format_datetime($v['created_at'])) ?> · <?= e($v['user_name']??'') ?></small></div><?php endforeach;?></div></div><?php if(can('special_reports.close')):?><div class="panel"><h2>Dokumentierter Nachtrag</h2><form method="post" action="<?= e(url('special-reports/'.$report['id'].'/addendum')) ?>" class="stack-form"><?= csrf_field() ?><label>Änderungsgrund*<input name="reason" required></label><label>Sachverhalt*<textarea name="facts" rows="7" required><?= e($report['facts']) ?></textarea></label><label>Maßnahmen<textarea name="measures_text" rows="3"><?= e($report['measures_text']??'') ?></textarea></label><label>Ergebnis<textarea name="result_text" rows="3"><?= e($report['result_text']??'') ?></textarea></label><button class="button primary" type="submit">Nachtrag als neue Version speichern</button></form></div><?php endif;?><?php endif;?>

<?php if(can('system.trash.manage')&&can('special_reports.delete')):?><div class="panel"><h2>Administration</h2><p>Der Sonderbericht kann in den zentralen Papierkorb verschoben werden. Versionen und Anlagen werden erst bei endgültiger Löschung entfernt.</p><form method="post" action="<?= e(url('admin/trash/special_reports/'.$report['id'].'/move')) ?>" data-confirm="Sonderbericht wirklich in den Papierkorb verschieben?"><?= csrf_field() ?><button class="button danger" type="submit">In Papierkorb verschieben</button></form></div><?php endif;?>
